 Get the common items between a and b

In [2]:
import numpy as np

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6,7])
b = np.array([7,2,10,2,7,4,9,4,9,8,6])
np.intersect1d(a,b)

array([2, 4, 6, 7])

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

out = np.where( a != np.intersect1d(a,b))
a = a[out]
print(a)
#correct way
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)


[1 2 3 4]


array([1, 2, 3, 4])

How to get the positions where elements of two arrays match?

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

In [37]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
out = np.where((a>=5) & (a<=10))
out = a[out]
print(out)

[ 6  9 10]


 How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.



In [39]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_maxx = np.vectorize(max, otypes=[float])
    
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])    

pair_maxx(a,b)
    

array([6., 7., 9., 8., 9., 7., 5.])