In [1]:
import numpy as np

How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.



In [6]:

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

In [8]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

In [10]:
arr = np.arange(9).reshape(3,3)
arr[::-1,]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.



In [12]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.



In [24]:
arr = np.random.randint(5,10,[5,3]) +np.random.random((5,3))

print(arr)

[[5.89765175 6.87679723 5.13709121]
 [8.6955859  9.02286552 8.7822663 ]
 [6.77330487 7.19515678 5.68941885]
 [6.05649338 9.70834288 7.26415897]
 [9.29205865 6.22134142 5.53765328]]
