In [1]:
import numpy as np

51. How to generate one-hot encodings for an array in numpy?
Difficulty Level L4

Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [11]:
np.random.seed(101)
arr = np.random.randint(1,4, size=6)
print(arr)

[2 3 2 2 2 1]


In [14]:
def one_hot_encoding(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i,k in enumerate(arr):
        out[i,k-1] = 1
    return out

In [15]:
one_hot_encoding(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
How to create row numbers grouped by a categorical variable?
Difficulty Level: L3

Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.



In [19]:
url = '/home/mihir/ML_practice/numpy101/archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',',dtype='str',usecols = 4)
species_small = np.sort(np.random.choice(iris, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [20]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small == val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]


 How to create groud ids based on a given categorical variable?
Difficulty Level: L4

Q. Create group ids based on a given categorical variable. Use the following sample from iris species as input.

In [25]:
output = []
uniqs = np.unique(species_small)
for val in uniqs:
    for s in species_small[species_small == val]:
        groupid = np.argwhere(uniqs == s).tolist()[0][0]
        output.append(groupid)
        
print(output)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]


How to rank items in an array using numpy?
Difficulty Level: L2

Q. Create the ranks for the given numeric array a.

In [26]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [ ]:
 How to rank items in an array using numpy?
Difficulty Level: L2

Q. Create the ranks for the given numeric array a.

In [27]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [28]:
print(a.argsort().argsort())
print('Array: ',a)

[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


How to rank items in a multidimensional array using numpy?
Difficulty Level: L3

Q. Create a rank array of the same shape as a given numeric array a.

In [30]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [31]:
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]
