In [1]:
import numpy as np

How to find the maximum value in each row of a numpy array 2d?
DifficultyLevel: L2

Q. Compute the maximum for each row in the given array.

In [5]:
np.random.seed(100)
a = np.random.randint(1,10,[5,3])
print(a)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


In [9]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [10]:
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 8, 6, 3, 9])

How to compute the min-by-max for each row for a numpy array 2d?
DifficultyLevel: L3



In [15]:
np.apply_along_axis(lambda x : np.min(x)/np.max(x), arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [ ]:
How to find the duplicate records in a numpy array?
Difficulty Level: L3

Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

In [17]:
np.random.seed(100)
a = np.random.randint(0,5,10)
print(a)

[0 0 3 0 2 4 2 2 2 2]


In [19]:
out = np.full(a.shape[0], True)
unique_pos = np.unique(a, return_index=True)[1]
print(unique_pos)
print(out)

[0 4 2 5]
[ True  True  True  True  True  True  True  True  True  True]


In [21]:
out[unique_pos] = False
print(out)

[False  True False  True False False  True  True  True  True]


 How to find the grouped mean in numpy?
Difficulty Level L3

Q. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array



In [22]:
url = '/home/mihir/ML_practice/numpy101/archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',',dtype='object')
names = ('sepallength','sepalwidth','petallength','petalwidth','species')

In [23]:
numeric_column = iris[:,1].astype('float')
grouping_column = iris[:,4]
[[group_val, numeric_column[grouping_column == group_val].mean()]for group_val in np.unique(grouping_column)]

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [27]:
op = []
for group_val in np.unique(grouping_column):
    op.append([group_val, numeric_column[grouping_column==group_val].mean()])
print(op)

[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]


How to convert a PIL image to numpy array?
Difficulty Level: L3

Q. Import the image from the following URL and convert it to a numpy array.

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [30]:
from io import BytesIO
from PIL import Image
import PIL, requests

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr = np.asarray(I)
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)