In [3]:
import numpy as np

6: Replace items that satisfy a condition without affecting 
    original array
    Replace all odd numbers in arr with -1 without changing arr

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range (0,arr.size):
    if arr[i]%2 == 1:
        arr[i] = arr[i]/arr[i]*-(1)
print(arr)
# this is wrong though output is equal, ding it as shown in guide

arr = np.arange(10)
out = np.where(arr % 2 == 1,-1,arr)
print(arr)
out
#numpy.where(condition, x, y): If condition true x else y
#important thing to learn is vector operation that is no need to traverse


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7: Reshape an array.
   1D array to 2D array

In [31]:
arr = np.arange(10)
arr = arr.reshape(-1, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


8: Stack arrays vertically

In [40]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([a,b])
print(c)
c = []
c = np.vstack([a,b])
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9:Stack array a and b horizontally

In [42]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

generate custom sequences in numpy without hardcoding
Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [44]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])