In [1]:
import numpy as np

How to convert numpy's datetime64 object to datetime's datetime object?
Difficulty Level: L2

Q. Convert numpy's datetime64 object to datetime's datetime object

In [3]:
dt64 = np.datetime64('2018-02-25 22:10:10')

In [4]:
from datetime import datetime
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

How to compute the moving average of a numpy array?
Difficulty Level: L3

Q. Compute the moving average of window size 3, for the given 1D array.



In [11]:
np.random.seed(100)

In [10]:
def moving_average(a,n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.random.randint(10, size=10)
print('array: ',Z)
moving_average(Z, n=3).round(2)

array:  [7 7 0 2 9 9 3 2 5 8]


array([4.67, 3.  , 3.67, 6.67, 7.  , 4.67, 3.33, 5.  ])

In [15]:
ret = np.cumsum(Z, dtype=float)
print(ret)
print(Z)

[ 7. 14. 14. 16. 25. 34. 37. 39. 44. 52.]
[7 7 0 2 9 9 3 2 5 8]


How to create a numpy array sequence given only the starting point, length and the step?
Difficulty Level: L2

Q. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers



In [17]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)
seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

How to fill in missing dates in an irregular series of numpy dates?
Difficulty Level: L3

Q. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

In [28]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'),2)
print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


In [34]:
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)
print(filled_in)

['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22']


How to create strides from a given 1D array?
Difficulty Level: L4

Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

In [37]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [47]:
def gen_stride(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)/stride_len)+1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, int(n_strides*stride_len), stride_len)])
gen_stride(arr,stride_len=2,window_len= 4)

array([array([0, 1, 2, 3]), array([2, 3, 4, 5]), array([4, 5, 6, 7]),
       array([6, 7, 8, 9]), array([ 8,  9, 10, 11]),
       array([10, 11, 12, 13]), array([12, 13, 14])], dtype=object)