In [1]:
import numpy as np

How to drop all missing values from a numpy array?
Difficulty Level: L2

Q. Drop all nan values from a 1D numpy array

Input:

np.array([1,2,3,np.nan,5,6,7,np.nan])



In [2]:
a = np.array([1,2,3,np.nan,4,5,6,np.nan,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 4., 5., 6.])

How to compute the euclidean distance between two arrays?
Difficulty Level: L3

Q. Compute the euclidean distance between two arrays a and b.



In [4]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [6]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

How to find all the local maxima (or peaks) in a 1d array?
Difficulty Level: L4

Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.



In [8]:
a = np.array([1,9,2,3,3,1,1,5,2,1,8,0,1,3,6,4,2,1])

In [11]:
doublediff = np.diff(np.sign(np.diff(a)))
peak_location = np.where(doublediff == -2)[0] + 1
print(peak_location)

[ 1  7 10 14]


In [14]:
print(np.diff(a))
print(np.diff(np.diff(a)))

[ 8 -7  1  0 -2  0  4 -3 -1  7 -8  1  2  3 -2 -2 -1]
[-15   8  -1  -2   2   4  -7   2   8 -15   9   1   1  -5   0   1]


How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?
Difficulty Level: L2



In [19]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [20]:
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [21]:
print(b_1d[:,None])

[[1]
 [2]
 [3]]


 How to find the index of n'th repetition of an item in an array
Difficulty Level L2

Q. Find the index of 5th repetition of number 1 in x.



In [26]:
x = np.array([1,2,1,1,3,1,1,2,1,3,1,5,1])
n=5
np.where(x == 1)[0][n-1]

6